### ISSUE TITLE
JS error in ETN app

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn-occurrences#32]
There is an error loading the Javascript libraries (and some of the css?) in the ETN app:

```
app.js?1.0:42 Uncaught Error: Module build failed: ModuleBuildError: Module build failed: Error: `sass-loader` requires `node-sass` >=4. Please install a compatible version.
    at Object.sassLoader (Z:\symfony\etn\node_modules\sass-loader\lib\loader.js:31:19)
    at runLoaders (Z:\symfony\etn\node_modules\webpack\lib\NormalModule.js:195:19)
    at Z:\symfony\etn\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at Z:\symfony\etn\node_modules\loader-runner\lib\LoaderRunner.js:230:18
    at runSyncOrAsync (Z:\symfony\etn\node_modules\loader-runner\lib\LoaderRunner.js:143:3)
    at iterateNormalLoaders (Z:\symfony\etn\node_modules\loader-runner\lib\LoaderRunner.js:229:2)
    at Z:\symfony\etn\node_modules\loader-runner\lib\LoaderRunner.js:202:4
    at Z:\symfony\etn\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:70:14
    at process.internalTickCallback (internal/process/next_tick.js:70:11)
    at Object.QFsf (http://www.lifewatch.be/etn/build/app.js?1.0:42:83486)
    at e (http://www.lifewatch.be/etn/build/app.js?1.0:1:101)
    at Object.012l (http://www.lifewatch.be/etn/build/app.js?1.0:1:524)
    at e (http://www.lifewatch.be/etn/build/app.js?1.0:1:101)
    at http://www.lifewatch.be/etn/build/app.js?1.0:1:462
    at http://www.lifewatch.be/etn/build/app.js?1.0:1:476
QFsf @ app.js?1.0:42
e @ app.js?1.0:1
012l @ app.js?1.0:1
e @ app.js?1.0:1
(anonymous) @ app.js?1.0:1
(anonymous) @ app.js?1.0:1
animals:655 Uncaught ReferenceError: $ is not defined
    at animals:655
(anonymous) @ animals:655
animals:1272 Uncaught ReferenceError: $ is not defined
    at animals:1272
```

The page currently looks like this for me:

<img width="833" alt="Screenshot 2019-04-02 at 12 16 05" src="https://user-images.githubusercontent.com/600993/55395067-2300c900-5541-11e9-8898-e2139eb602ed.png">

**Comment by peterdesmet** [comment]
Solved.
